### ISSUE TITLE
Bug: various incorrect rule violations for the first line

### ISSUE THREAD

**Issue by chrisgrieser** [bmatcuk/stylelint-lsp#36]
For the first line of my css file, I get various rule violations, which do not occur when I run stlylelint normally via the terminal. They even include rules I haven't activated within my stlyelintrc, for some reason?

<img width="1202" alt="Pasted image 2022-10-10 18 37 22" src="https://user-images.githubusercontent.com/73286100/194914267-cf87e14b-5030-4664-b535-7fce282f3cf0.png">

**Comment by bmatcuk** [comment]
I know this is old, but did you ever figure it out? My guess is that stylelint-lsp was loading the wrong stylelintrc config file.

**Comment by chrisgrieser** [comment]
nope, never figured it out. Was still not working last time I tried

**Comment by chrisgrieser** [comment]
Ok, so I found the time to look into it again, and… The issue is gone 🙈

Everything seems to work fine now. Weird. Gonna close this then, will re-open if the issue re-occurs.
