### ISSUE TITLE
Bug: new rule not supported (`lightness-notation`)

### ISSUE THREAD

**Issue by chrisgrieser** [bmatcuk/stylelint-lsp#45]
Recently, I started getting this error in the first line of every file:

```
Unknown rule lightness-notation. stylelintplus: lightness-notation
```

Looking into it, [the rule does exist](https://stylelint.io/user-guide/rules/lightness-notation/), but appears to be [rather new](https://github.com/stylelint/stylelint/pull/7366). 

Manually running stylint `16.1.0`, reports no issue. I am on stylelint-lsp `2.0.0`.

---

While some delay for new rules in stylint to appear in the stylelint-lsp is no big deal, the fact that a new rule results in errors in the stylelint-lsp is indeed somewhat annoying, and something that you should be able to at least deactivate? Looking at the docs, there seems to be no way to disable the [unknown-rule-error](https://stylelint.io/user-guide/errors/#unknown-rule-error), at least as far as I can tell. Maybe the stylelint-lsp could add a small stopgap here or something?

**Comment by bmatcuk** [comment]
Hmm, I would guess that the issue is that stylelint-lsp is using the built-in stylelint dependency, which is on v15, instead of your project's dependency, which must be on 16.1.0. Are you using something other than `npm` as your package manager?

**Comment by chrisgrieser** [comment]
Yeah, I am using npm. 

though I just figured out that the error comes from `stylelint-config-standard` adding `lightness-notation`, and that explicitly disabling the rule in my config via `lightness-notation: null` is a simple solution for this already
