### ISSUE TITLE
Underlines at specific column number not showing in Neovim

### ISSUE THREAD

**Issue by benfrain** [bmatcuk/stylelint-lsp#46]
Thanks for this project, it's great having stylelint feedback in the editor. I am trying to troubleshoot getting underlines appearing in Neovim. 

I get the line No. called out in the gutter, but not the specific range on the columns (such as would allow you to underline the problem area). Unsure if this is a Neovim config thing? When I jump from diagnostic point to diagnostic point, it jumps to the correct column start point.

Saw this and wondered if it might be this: https://github.com/mfussenegger/nvim-lint/issues/394 essentially the LSP not providing `end_col` so ranges can be established.

VSCode shows the column correctly, which kind of makes me assume this is Neovim specific 🤷‍♂️

Not terminal specific as tried with both Kitty and WezTerm

**Comment by benfrain** [comment]
Sorry, ignore, using VSCode I can see that it gets column specific markings so assume this is a Neovim thing.

**Comment by benfrain** [comment]
Re-opening but updating the title as not sure it is anything to do with end_col

**Comment by bmatcuk** [comment]
Looks like I wasn't passing an end line/column with the diagnostics... I just released v2.0.1 that I _think_ will fix this issue. Let me know!

**Comment by benfrain** [comment]
Hi @bmatcuk thanks for taking a look, not checked exhaustively but 2.0.1 seems to have sorted it:

<img width="371" alt="image" src="https://github.com/user-attachments/assets/46e1e40f-e1d1-4b75-a488-ced6acdfc1a1">

Thanks so much for the speedy fix

**Comment by bmatcuk** [comment]
Nice! Glad that worked for ya =)
