### ISSUE TITLE
[question] How it differs from competition

### ISSUE THREAD

**Issue by rchl** [bmatcuk/stylelint-lsp#8]
Sorry if that's an inappropriate question. :)

I was wondering how your server compares to the one included with https://github.com/stylelint/vscode-stylelint. The advantage of yours that I can see up-front is that it's usable with all editors while the other one would have to be adapted (haven't found any ready-made npm package for it).

What about functionality? Are you aware of any differences?
I could, of course, test it all myself but figured that maybe you can "advertise" it better if you know your competition. :)

**Comment by bmatcuk** [comment]
I think you hit on the major advantage in your question: it's usable with all editors. I don't use vscode so I haven't tried vscode-stylelint.

**Comment by rchl** [comment]
After some testing I've noticed those differences also:
 - `vscode-stylelint` supports "code actions on save" (a client feature really)
 - `vscode-stylelint` returns formatting changes as **TextEdit** while this one returns a **command** which requires extra round-trip to the server to handle.
